
CREATE TABLE IF NOT EXISTS planner(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	task TEXT NOT NULL,
	category TEXT  NOT NULL  DEFAULT 'Без категории',
	deadline DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


